exiting if JSON schema for public-implementations is invalid

diff --git a/.github/workflows/report.yml b/.github/workflows/report.yml
--- a/.github/workflows/report.yml
+++ b/.github/workflows/report.yml
@@ -104,8 +104,15 @@ jobs:
             done | \
           jq -s 'add' > public-implementations
 
-      - name: Validate public-implementations against a JSON Schema
-        run: bowtie validate -i python-jsonschema bowtie/schemas/public-implementations.json public-implementations
+      - name: Validate public-implementations against its corresponding JSON Schema
+        run: |
+          VALIDATION=$(bowtie validate --expect valid -i python-jsonschema bowtie/schemas/public-implementations.json public-implementations)
+          SUMMARY=$(echo "$VALIDATION" | bowtie summary --show failures --format json)
+          if [ $(echo "$SUMMARY" | \
+                 jq 'all(.[]; .[1].failed == 0 and .[1].errored == 0 and .[1].skipped == 0)') == false ]; then
+              echo "public-implementations file is invalid under its JSON Schema"
+              exit 1
+          fi
 
       - uses: actions/upload-artifact@v4
         with:
@@ -140,7 +147,7 @@ jobs:
           path: site/
           merge-multiple: true
 
-      - name: Include Implementation Metadata
+      - name: Include Implementations Metadata (Private API)
         uses: actions/download-artifact@v4
         with:
           name: implementations
@@ -149,7 +156,7 @@ jobs:
       - name: Create a Public Directory Structure for JSON Schema Org
         run: mkdir -p site/v1/json-schema-org
 
-      - name: Include Public Implementation Metadata
+      - name: Include Public Implementations Metadata (Public API)
         uses: actions/download-artifact@v4
         with:
           name: public-implementations
